server:
  port: 80

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: serials
          uri: lb://serial-service
          predicates:
            - Path=/serials/**

        - id: users
          uri: lb://user-service
          predicates:
            - Path=/serials/**
        - id: serials-swagger
          uri: lb://serial-service/swagger-ui.html
          predicates:
            - Path=/serial/api

eureka:
  client:
    service-url.default: http://localhost:8761/eureka
